XENONnT/saltax

saltax/contexts.py

- Downgraded `cmt_version` in `sxenonnt` so that we won't trigger bug.
- Removed useless `wfsim_registry`

Default `cmt_version` downgrade

---

saltax/contexts.py

Debugged `sxenonnt('salt')`
- Fixed dictionary bug in `update`
- added placeholder for `gain_model_mc`
```python
st = saltax.contexts.sxenonnt('salt')
st.config
{'detector': 'XENONnT',
'fax_config': 'fax_config_nt_sr0_v4.json',
'check_raw_record_overlaps': True,
'n_tpc_pmts': 494,
'n_top_pmts': 253,
'gain_model': '[list-to-array://xedocs://pmt_area_to_pes?as_list=True&sort=pmt&detector=tpc&run_id=plugin.run_id&version=v9&attr=value](list-to-array://xedocs//pmt_area_to_pes?as_list=True&sort=pmt&detector=tpc&run_id=plugin.run_id&version=v9&attr=value)',
'gain_model_nv': 'cmt://to_pe_model_nv?run_id=026000&version=v4',
'gain_model_mv': …
```

Debug sxenonnt in salt mode

---

saltax/plugins/s_raw_records.py

Require that no instruction should be actually used to simulate in the last 50ms of a chunk.
Potential risk: part of the instruction (anything in the last 50ms of a chunk)  will NOT be simulated and seems as missing. We don't want to have this misunderstood by PEMA.
Manually remove instructions in the last 50ms of each chunk.
```python
instructions = instructions[(instructions['time'] >= start) & 
(instructions['time'] < end)] # Probably need safeguard here
(instructions['time'] < end-NS_NO_INSTRUCTION_BEFORE_CHUNK_END)]
```
- _On …

added safeguard

---

saltax/plugins/s_raw_records.py

Added safeguard in chunk timing range so we don't explode the last chunk time range.
Hardcoded: `NS_NO_INSTRUCTION_BEFORE_CHUNK_END = 5e7`

Added safeguard in chunk timing range

---

notebooks/example.ipynb
saltax/match/match.py

- Using PEMA matching in selection, but requiring S1 only. 
- Added example notebook
Requiring S1 to be `found` by `pema`.

Match s1 only

---

saltax/plugins/s_peaklets.py

Trying to tackle #67. Transplanted straxen PR [Fixing hitlets boundary out of chunk](https://github.com/XENONnT/straxen/pull/1328) and [Copy time of hitlets before clip it](https://github.com/XENONnT/straxen/pull/1338).

Hitlets boundary

---

jobs/config.ini
jobs/job.py
saltax/instructions/generator.py

- More options in job config to make records skipped and delete them after computation finished to save sapce
- more options to turn off simulation computation
- tunned SE generator default rate

Skip records and tune SE generator

---

saltax/plugins/s_peaklets.py

Currently there are some waveforms like this, which gives infinite `merged_s2s` area as well as a bad point in data. See this
The root of this issue is suspected to lie in the absence of `lone_hits` channel shifting. Without it, in `merged_s2s` when adding `lone_hits` [here](https://github.com/AxFoundation/strax/blob/93e4a093c6d8788821e91a9d4631bd60e0dfd81f/strax/processing/peak_merging.py#L189-L197) by sealing `to_pe` like [this](https://github.com/XENONnT/straxen/blob/fb1ae7681eb743854adfcb252094a86d4ef973f0/straxen/plugins/merged_s2s/merged_s2s.py#L70), we may have a bad point with value `np.inf`. It is not clear why it is infinite, but …

Debug Infinite `lone_hits` area in `merged_s2s`

---

jobs/job.py
saltax/contexts.py
saltax/instructions/generator.py

- Increased default salting rate
- avoid regenerating instructions.
- Added a bit more debugging friendly info
For avoiding regenerating instructions, we require file existence check before generating instruction.

Increased default salting rate and avoid regenerating instructions

---

saltax/contexts.py
saltax/instructions/generator.py
saltax/plugins/s_peaklets.py

- In #85 I introduced a bug for shifting `lone_hits` channel number. I applied the subtraction to every channel, which leads to the fact that the data `lone_hits` will have negative channel. 
- Improved some bad logic in ambe generator, which may lead to selecting an empty instruction to pass.

Fixed a fatal bug in `lone_hits` channel shifting

---

saltax/plugins/s_peaklets.py

We introduced a bug again in #90 . Now it can be fixed. Such a classical numpy confusion...

bug fix in lone_hits shift

---

jobs/job.py
saltax/contexts.py
saltax/match/utils.py
saltax/plugins/s_raw_records.py

- Trying to resolve #105. Just added a hard cut on instructions right after chunk starts. Don't have a good reason, but just to make it the same as in chunk end.
- Added more to-do plugins for SE case, since we want to track shadow and ambience

Added safeguard after chunk_start

---

requirements.txt

Just to make the installation work. However, it is still wrong because we don't have a 1.2.2 wfsim on pypi. We want to solve it later.

Removed wfsim version requirement

---

README.md
saltax/__init__.py
saltax/contexts.py
saltax/instructions/__init__.py
saltax/match/__init__.py
setup.py

- Bumped version to `v0.1.2`
- Adding runid validation in context
- Removed `corrections_run_id`

Decouple runid from lineage

---

saltax/instructions/generator.py

So that we won't have file name conflict problem for same generator with different energy.

Include `en_range` in instruction file name

---

saltax/match/utils.py

Was hardcoded in a wrong value. Now fixed.

Fixed z min in `get_cut_eff`

---

saltax/contexts.py

Before this PR, we are somehow always simulating ER type in saltax when using fuse! The problem here is the missing `recoil` in `generator_func`. 
This leads to the always-beta nest type:
```
vim 051911-0-flat-0.2_45-all-100.csv
event_number,type,time,x,y,z,amp,recoil,e_dep,tot_e,g4id,vol_id,local_field,n_excitons,x_pri,y_pri,z_pri
1,1,1681822424117999872,-46.468105,16.676464,-65.51044,287,8,5.1959395,0.0,0,0,21.985272256943297,31,0.0,0.0,0.0
1,2,1681822424117999872,-46.468105,16.676464,-65.51044,132,8,5.1959395,0.0,0,0,21.985272256943297,31,0.0,0.0,0.0
2,1,1681822424127999872,-36.150017,34.574623,-104.82069,595,8,12.245673,0.0,0,0,21.803115082164446,80,0.0,0.0,0.0
2,2,1681822424127999872,-36.150017,34.574623,-104.82069,270,8,12.245673,0.0,0,0,21.803115082164446,80,0.0,0.0,0.0
```

Bug fix in fuse generator

---

jobs/job.py
saltax/contexts.py

BE VERY CAUTIOUS. This functionality will force unblind the sprinkled and simulation datasets when `unblind` is on.

Force unblind

---

saltax/contexts.py

This fix is necessary as `fuse.context.microphysics_plugins` has been replaced by three different sets, since [this fuse commit ](https://github.com/XENONnT/fuse/commit/83678d3aefff25bcf8463090487cf327fd7d1cf4).

Compatibility with fuse 1.4.3

---

jobs/job.py
notebooks/example_minimal.ipynb
saltax/README.md

The context based on fuse is developed after the context based on wfsim. The naming fashion in `saltax` is to prefix an `s` or `S` in front of the modified straxen / fuse class, like `SPMTResponseAndDAQ` and `SChunkCsvInput`. But for historical reasons (fuse after wfsim), fuse context was named `fxenonnt`.
So it is natural to rename `fxenonnt` to `sxenonnt` after `wfsim` is removed in https://github.com/XENONnT/saltax/pull/160

Rename `fxenonnt` to `sxenonnt`

---

pyproject.toml

The issue blocked https://github.com/XENONnT/saltax/actions/runs/15988492518

Fix `classifiers` in `pyproject.toml`
