XENONnT/saltax

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_templates.md
=> Copied Github Templates from `straxen`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Adding feature request template to issue.
Followed Github official tutorial to add a markdown file.
Expecting something like this. <img width="633" alt="image" src="https://github.com/FaroutYLq/saltax/assets/47046530/a591ab1d-27e2-42d2-8c21-076e23afac8a">
=> added feature request template

.github/pull_request_template.md
Adding PR tag check to PR template.
Just adding one block in the markdown file.
Now it should have this:
=> Added tag check for PR tempalte

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Adding italic fonts to issue templates.
Trivial.
Trivial.
=> Italic template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
* Update feature_request.md
* Update bug_report.md
* Update bug_report.md
* Update feature_request.md
=> Italic template (#9)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, requirements.txt, saltax/__init__.py, saltax/contexts.py, saltax/plugins/__init__.py, saltax/plugins/s_raw_records.py, saltax/plugins/s_records.py, setup.py
=> Merge main into records

tests/test_contexts.py
=> Minimal tests

saltax/contexts.py
Debugged `saltax.sxenonnt(saltax_mode='data')`
Added copy in `straxen` options and config
```python
std = saltax.contexts.sxenonnt('data')
```
=> Copy in `straxen` options and config

saltax/contexts.py
Added docstr for `contexts.py`.
=> Docstr for contexts

.github/scripts/create-utilix-config.sh, .github/workflows/test_package.yml, extra_requirements/requirements-tests.txt
Stolen cutax's [test workflow](https://github.com/XENONnT/cutax/tree/master/.github)
Not tested yet.
=> Minimally modified from cutax's test workflows

.github/dependabot.yml
Trying to solve #12 by copying[ dependabot workflow from base_environment ](https://github.com/XENONnT/base_environment/blob/master/.github/dependabot.yml)
=> Stolen depandabot from base_environment

requirements.txt
Remove `requirements.txt` so that we don't trigger installation problem on GitHub auto test workflow
=> Removed cutax from requirement

saltax/plugins/s_raw_records.py
Debugged raw_records_simu
Hardcoded `ChunkRawRecords` in `saltax` to replace `raw_records` -> `raw_records_simu`
=> Debugged raw_records_simu

saltax/contexts.py, saltax/plugins/s_raw_records.py, saltax/plugins/s_records.py
- Modified `ChunkRawRecords` so that it won't be really using iterator features. (Need to add security check on buffer size later!)
- `records` can be loaded now since `raw_records` and `raw_records_simu` have been forced to share time. (Need to study if the instruction chunking is safe later)
- Manually overwrite `is_ready`
- Make `raw_records_simu` dependent on `raw_records`.
- Need to figure out how to download data on remote testing first.
=> Debug records

saltax/instructions/generator.py
=> Added SE generator

saltax/contexts.py, saltax/match/visual.py, saltax/plugins/s_peaklets.py
Added pema plugin auto registering.
=> Register pema

jobs/config.ini, saltax/instructions/generator.py
Implemented AmBe generator, which takes instruction from full chain epix-processed instructions saved locally.
=> Ambe generator

jobs/config.ini, saltax/match/match.py, saltax/match/utils.py
Rewritten `match_events` to save indices. Need to update example notebook!! Also need to remove deprecated functions
=> Rewritten matching events to enable event building efficiency study

.pre-commit-config.yaml, saltax/__init__.py, saltax/instructions/__init__.py, saltax/match/__init__.py, setup.py
=> Addicting pre-commit features for better style control

jobs/job.py, saltax/contexts.py
Trying to solve problems in #107. This is a dirty patch but we will refactor `wfsim` and `pema` related parts very soonish, so it doesn't matter.
=> Turn off pema

notebooks/README.md, notebooks/example_minimal.ipynb, saltax/__init__.py, saltax/instructions/__init__.py, saltax/match/__init__.py, setup.py
- Added minimal example as a quick start tutorial.
- Bumped version to `v0.1.1`
=> Minimal example notebook

notebooks/example_minimal.ipynb, requirements.txt
As a permanent solution to #68
=> Require wfsim>=1.2.2

jobs/job.py, saltax/instructions/generator.py
To solve #119. 
- Modularized functionalities
- Adopted logging instead of printing
- Killed redundant commands
=> Refactor `job.py`

jobs/job.py, saltax/contexts.py, saltax/instructions/generator.py
=> Replaced print with logging in `contexts.py`

jobs/job.py, saltax/plugins/peaklets.py, saltax/plugins/records.py
=> Inherit straxen records and peaklets

jobs/job.py, saltax/instructions/generator.py
=> Adding setting printout in jobs logs

jobs/README.md, saltax/contexts.py, saltax/plugins/f_raw_records.py, saltax/plugins/s_raw_records.py
Added more description on how to set the logging level. Also cleaned up a bit logging level in each script.
=> Logging level and tutorial

saltax/match/utils.py
There was a problem in which I iterated the color twice in one loop
=> Debugged colors in `get_cut_eff`

jobs/job.py, saltax/contexts.py
`cuts_basic` becomes tricky in latest environments, and we don't necessarily get them produced to begin with!
=> Dont auto register cuts

saltax/instructions/generator.py
Quickly resolve #148. No physics result is expected to be affected at all.
=> Explicitly assign local field in AmBe/YBe generator

.bumpversion.cfg, .github/workflows/test_package.yml, pytest.ini, requirements.txt, setup.py, tests/test_basics.py
A further fix of https://github.com/XENONnT/saltax/pull/157
=> Fix version number in `setup.py`

notebooks/example_minimal.ipynb, saltax/plugins/records.py
Close https://github.com/XENONnT/saltax/issues/168
=> Sort `records`

saltax/instructions/generator.py
`doc["start"]` and `doc["end"]` are timezone unaware and in UTC
=> Simplify timezone conversion

saltax/patches/straxen_2.py, saltax/patches/straxen_3.py
Close: https://github.com/XENONnT/saltax/issues/186
The issue is already fixed by https://github.com/XENONnT/saltax/blob/869516079b764f71b641294856f398ea89a8888c/saltax/patches/straxen_2.py#L80
=> Remove FIXME comment about `data_top` because it is already done

saltax/match/utils.py
Some codes were changed accidentally by https://github.com/XENONnT/saltax/pull/190. This PR reverts the unnecessary change.
=> Replace `BASIC_CUTS` in variable names by `all_cuts`
